# LeetCode Local Practice Configuration

[paths]
# Directory where solution templates are stored by default
solutions_dir = "solutions"
# Directory where custom test cases are stored
test_cases_dir = "test_cases"

[preferences]
# Default difficulty level for filtering (EASY, MEDIUM, HARD, or ALL)
default_difficulty = "ALL"
# Default problem category for filtering
default_category = "ALL"
# Default template style (basic, detailed)
template_style = "detailed"
# Number of problems to display per page in browse mode
page_size = 10

[testing]
# Print detailed output for each test case
verbose = true
# Time each solution
time_solutions = true
# Maximum execution time for each test (seconds)
timeout = 5

[problems]
# Whether to include locked LeetCode problems
include_locked = false
# Custom difficulty coloring
color_easy = "green"
color_medium = "yellow"
color_hard = "red"

[leetcode75]
# Whether to restrict the problems to LeetCode 75 list only
restrict_to_leetcode75 = true