# LeetCode Local Practice Configuration

[paths]
# Directory where solution templates are stored by default
solutions_dir = "solutions"
# Directory where custom test cases are stored
test_cases_dir = "test_cases"

[preferences]
# Default difficulty level for filtering (EASY, MEDIUM, HARD, or ALL)
default_difficulty = "ALL"
# Default problem category for filtering
default_category = "ALL"
# Default template style (basic, detailed)
template_style = "detailed"
# Number of problems to display per page in browse mode
page_size = 10

[testing]
# Print detailed output 